# Generated by Django 4.1.4 on 2022-12-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Team Name')),
                ('location', models.CharField(max_length=255, verbose_name='Team Location')),
                ('description', models.CharField(max_length=255, verbose_name='Team Description')),
                ('slug', models.SlugField(max_length=255, verbose_name='Team Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Team Images/%Y/%m/%d', verbose_name='Team Image')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Team Thumbnails/%Y/%m/%d', verbose_name='Team Thumbnail')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Player Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Player Last Name')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Player Patronymic')),
                ('birthday', models.DateTimeField()),
                ('position', models.CharField(max_length=255, verbose_name='Player Position')),
                ('matches', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Players Images/%Y/%m/%d', verbose_name='Player Image')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Players Thumbnails/%Y/%m/%d', verbose_name='Player Thumbnail')),
                ('slug', models.SlugField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.team')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
