# Generated by Django 4.1.4 on 2022-12-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(default='Available', max_length=255, verbose_name='Player Status'),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(default='', verbose_name='Team Description'),
        ),
    ]
