# Generated by Django 4.1.4 on 2022-12-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player_red_cards_player_status_player_yellow_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='red_cards',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(verbose_name='Team Description'),
        ),
    ]
