# Generated by Django 4.1.4 on 2022-12-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_player_red_cards_alter_player_yellow_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.CharField(default='dd.mm.yyyy', max_length=10),
        ),
    ]
