# Generated by Django 4.1.4 on 2022-12-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_player_red_cards_alter_player_yellow_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Disqualified', 'Disqualified'), ('Injured', 'Injured')], default='Available', max_length=255, verbose_name='Player Status'),
        ),
    ]
