# Generated by Django 4.1.4 on 2022-12-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_player_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.CharField(default='DD.MM.YYYY', max_length=10),
        ),
    ]
