# Generated by Django 4.1.4 on 2022-12-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMainTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_theme', models.CharField(choices=[], max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'ordering': ('main_theme',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999, verbose_name='Blog Title')),
                ('text', models.TextField(verbose_name='Blog Text')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='Blog Images/%Y/%m/%d')),
                ('blog_thumbnail', models.ImageField(blank=True, null=True, upload_to='Blog Thumbnails/%Y/%m/%d')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.blogmaintheme')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
