# Generated by Django 4.1.4 on 2022-12-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmaintheme',
            name='main_theme',
            field=models.CharField(choices=[('Пляжный футбол', 'Пляжный футбол'), ('Футзал', 'Футзал'), ('Большой футбол', 'Большой футбол')], max_length=255),
        ),
    ]
